language: c
compiler:
  - gcc
  - clang
notifications:
  irc:
    channels:
      - "chat.freenode.net#beagledrone"
    template:
      - "(%{branch} - %{commit} : %{author}): %{message}"
script: cd firmware/tests && make
